services:
  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    container_name: frontend-admin
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
